version: '3.1'

services:
  iahspeurope-wp:
    image: wordpress:5.3
    restart: always
    ports:
      - 6901:80
    environment:
      WORDPRESS_DB_HOST: iahspeurope-mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - "./artifacts/wp-content:/var/www/html/wp-content"
    networks:
      - iahspeurope

  iahspeurope-mysql:
    image: mysql:5.7
    restart: always
    ports:
      # We're opening this so that we can use our MySQL clients.
      - 6902:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - iahspeurope

volumes:
  db:

networks:
  iahspeurope:
